spring:
  profiles:
    active: local
---
server:
  port: 8090

spring:
  profile: local
  db:
    host: localhost
    port: 3306
  datasource:
    url: jdbc:mariadb://${spring.db.host}:${spring.db.port}/blueintel_parking?characterEncoding=UTF-8&allowMultiQueries=true
    username: user_rest
    password: elwlxjffh31!@
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  liquibase:
    change-log: classpath:/db/changelog-master.xml
    drop-first: false
    enabled: true